# MapR Volume Driver Plugin for Kubernetes

# Using the MapR Volume Driver Plugin for dynamic provisioning

# Simple busybox container

# Pod
kind: Pod
apiVersion: v1
metadata:
  name: test-secure-provisioner
  namespace: mapr-secure
spec:
#  nodeSelector:
#    kubernetes.io/hostname: node01
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "100000"
    imagePullPolicy: Always
    volumeMounts:
    - name: maprfs-pvc
      mountPath: "/dynvolume"
  restartPolicy: "Never"
  volumes:
  - name: maprfs-pvc
    persistentVolumeClaim:
      claimName: maprfs-pvc-busybox


 