# MapR Volume Driver Plugin for Kubernetes

# Using the MapR Volume Driver Plugin for dynamic provisioning

# Provisioning: dynamic
# Container:    busybox

# MapR Apps Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: mapr-apps
  labels:
    name: mapr-apps

# MapR Apps ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mapr-apps-sa
  namespace: mapr-apps


# Secret to authenticate with MapR Converged Data Platform
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-provisioner-secrets
  namespace: mapr-apps
type: Opaque
data:
# base64 encoding: "echo -n '<username/password>' | base64" eg:
# echo -n 'mapr' | base64
  MAPR_CLUSTER_USER: "bWFwcg=="
  MAPR_CLUSTER_PASSWORD: "bWFwcg=="
# echo -n 'user01' | base64
#  MAPR_CLUSTER_USER: "dXNlcjAx"
#  MAPR_CLUSTER_PASSWORD: "dXNlcjAx"


# Ticket to authenticate with MapR Converged Data Platform
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-ticket-secret
  namespace: mapr-apps
type: Opaque
data:
# To create a Ticket:
# 1. maprlogin password -user mapr
# 2. echo -n $(cat /tmp/maprticket_####) | base64
# 3. combine 6 lines base64 output in single CONTAINER_TICKET line:
  # user: mapr
  CONTAINER_TICKET: ZGVtby5tYXByLmNvbSBlNy9JWUp4SXI2b25odEx6U294bFBoNEdvRlZDb0RoMElJKzV6eUN3clNvY1ZLdWNPUEN4WkwvTjd0L0ZYL3lKcTh5V0NqTUEyT1gzNzNIcVdscXFQdWxYM1MxVjRYckxCNndxUUlOOFRydVlNSW9QL0tmdXQxbmlPRFNNZllFNURvWGVMRTUvWGVuM1luT2tpRGhSTkVoajhJallpUXBMNEhaN1hmSzdpd1FhNUVPVVpkbzhzWHBobXZzcEZFOVkyakhqc2lSaTlFT0VSdFQycUhFT3hmSVdkRi9qaVNCWkVqdTBWbUlnQ05VOEUzVEIva1ltMHNvVWJONnFNQ1FFNndEaTZoMzI5b25NTG9qbmFMRmxWS0l1amZFeDFMQT0=
  # user: user01
  #CONTAINER_TICKET: ZGVtby5tYXByLmNvbSBXMjZjSmxqd2xVZTFXYUV6bkF6d0ZPbjZUMzk5TWU5Njg1a2NMc2g2eWRjUW1uaDNROExxb2xBVm1FV0s2OEdXWjRoTFVVazRLcmRnbE94TTAxT1plYXE4akRLbVRzdVljRXBnU1lUVTVnNVh6dFA3N1drYUtBckpZb1JXR1ljRnBadEFOL0llWldybTR1czJJVjhEakNZYUhyVDhCbDMvTzJpZlVaME1rbElmUXREUE9BMHVldURwKzltUWd1ZjhGQjNpbjA3R3cybWRmNG9JRDNSUnpndHRxYVZuakVwWlBRWXg0cCtoVytEc1g5SGtwMU9LOXFhOFpFWGQ3bEg3ZkpPMmRQMUF0eHdyYkU4NEdJZ3dKRUE9

# StorageClass for MapR Converged Data Platform
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: maprfs-sc-busybox-secure-dynamic
   namespace: mapr-apps
provisioner: mapr.com/maprfs
parameters:
    # Configure below MapR cluster details to reflect your MapR cluster configuration
    restServers: "172.16.4.203:8443"
    cldbHosts: "172.16.4.203"
    cluster: "demo.mapr.com"
    securityType: "secure"
    ticketSecretName: "mapr-ticket-secret"
    ticketSecretNamespace: "mapr-apps"
    maprSecretName: "mapr-provisioner-secrets"
    maprSecretNamespace: "mapr-apps"
    namePrefix: "busybox"
    mountPrefix: "/busybox"
    reclaimPolicy: "Retain"
    advisoryquota: "100M"
    type: "rw"
    mount: "1"


# PersistentVolumeClaim for MapR Converged Data Platform
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maprfs-pvc-busybox-secure-dynamic
  namespace: mapr-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: maprfs-sc-busybox-secure-dynamic
  resources:
    requests:
      storage: 300M
