# MapR Volume Driver Plugin for Kubernetes

# Using the MapR Volume Driver Plugin for STATIC provisioning

# Provisioning: Static
# Container:    Busybox

# Pod
---
kind: Pod
apiVersion: v1
metadata:
  name: mapr-k8s-busybox
  namespace: mapr-apps
spec:
#  nodeSelector:
#    kubernetes.io/hostname: node01
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "100000"
    imagePullPolicy: Always
    volumeMounts:
    - name: maprfs-pvc
      mountPath: "/mapr"
  volumes:
  - name: maprfs-pvc
    persistentVolumeClaim:
      claimName: maprfs-pvc-busybox-secure-static
